### ISSUE TITLE
Won't loop?

### ISSUE THREAD

**Issue by mcalnd70** [bobbyiliev/bash-ssl-checker-tool#6]
Hi Bobby - this is a great tool - I've also been using a tool called 'aha' to output it to a html page for our teams here to look at

One thing I found though is that it appears impossible to use '**ssl**' in a Bash loop? 

I was planning on having a list of sites a script would run through... for example a  **ssl.list** file with contents like...

```
www.microsoft.com
www.google.com
```

I've tried many loops and tests, but the loop seems to give up after the first invocation of the **ssl** command

Here are the contents of my **/sslchecker** folder

```
ls -la /sslchecker
total 24
drwxr-xr-x  2 root root 4096 Nov 24 13:10 .
drwxr-xr-x 25 root root 4096 Nov 24 13:10 ..
-rwxr-xr--  1 root root 4874 Nov 24 13:10 ssl
-rw-r--r--  1 root root   61 Nov 24 13:10 ssl.list
-rwxr-xr--  1 root root  505 Nov 24 13:10 ssl_checker.sh
```

The **ssl.list** file

```
www.microsoft.com
www.google.com
```

The **ssl_checker.sh** script

```
#! /bin/bash
cat /sslchecker/ssl.list | while read websiteurl
do
        echo loop start for $websiteurl
        /sslchecker/ssl $websiteurl
        echo loop end for $websiteurl
done
```

This will only do the first websitrurl - being www.microsoft.com and then the loop ends

Commenting out the **ssl** command - .e.g. 

```
#! /bin/bash
cat /sslchecker/ssl.list | while read websiteurl
do
        echo loop start for $websiteurl
        #/sslchecker/ssl $websiteurl
        echo loop end for $websiteurl
done
```

...reads...

```
loop start for www.microsoft.com
loop end for www.microsoft.com
loop start for www.google.com
loop end for www.google.com
```

Thanks

Neil

**Comment by bobbyiliev** [comment]
Hi there,

Happy to see that this is actually being used!

I've just committed a file called `ssl_check_loop.sh` where I use a for loop rather than the `while read` one. Seems to be working as expected/

Feel free to pull the latest changes and give it a go!

**Comment by mcalnd70** [comment]
Perfect - yes that change of loop seem to fix it - thanks for looking at it - Best Regards - Neil
